### PR TITLE
Fixes issue with IE8 not having a es5-sham for Object.defineProperty 

### PR DESCRIPTION
**Pull request by chiefy**
BreezeJS claims to be IE8 compatible with the inclusion of es5-shim.js and es5-sham.js, but I have found it would throw exceptions when trying to use Object.defineProperty. I have simply added a try/catch block around these calls and resort to simple assignment.

### CODE REVIEW

**Comment by korada** [comment]
Awesome. I've been banging my head to fix this issue. Thanks a ton.

**Comment by jtraband** [comment]
Unfortunately, shimming in a version of defineProperty that only works with DOM nodes isn't really a fix. But the idea of throwing a 'better' exception might be something we put in a later release.

**Comment by chiefy** [comment]
You should remove the IE8 logo from the list of your supported browsers.

**Comment by jtraband** [comment]
We have a number of customers using IE8 with Breeze and the ES5 shims. There was a bug in 1.4.1 that is now fixed that was causing IE8 issues.  Have you tried Breeze 1.4.2 with IE8?

**Comment by jfgrtsn** [comment]
Does this mean Breeze + Angular + IE8 is supported again? Or is that combo still a no-go?

**Comment by johnlantz** [comment]
Unfortunately no. The UserVoice topic here has more details:

https://breezejs.uservoice.com/forums/173093-breeze-feature-suggestions/suggestions/3532726-fix-angular-todo-example-so-that-it-works-with-

**Comment by jtraband** [comment]
Breeze + Angular has never worked with IE8 because we need full support for Object.defineProperty and IE8 does not provide this and neither can any shim.  Basically IE8's defineProperty implementation is severely limited and not shimable.  So this is a permanent no go. But....

What does work is Breeze + Knockout + IE8 or Breeze.+ Backbone + IE8 because neither the knockout or backbone adapters require Object.defineProperty.

**Comment by chiefy** [comment]
@johnlantz @jeffgarretson My fork works with IE8 + Angular. It's clearly not the greatest solution, but it works for now.

**Comment by chiefy** [comment]
@jtraband FYI http://todo.breezejs.com/ doesn't work in IE8 right now.

**Comment by KenVanGilbergen** [comment]
I fixed this exactly the same way for my 'lte IE 8' breeze include. I understand this can not be added to the master, but at least this way we can still support it. Tx

**Comment by jtraband** [comment]
Take a look at Breeze 1.4.5.  I think it's fixed there but with a different mechanism.

**Pull request closed without merging**
