### PR TITLE
Entity Framework 6.0.1 Added.

### PR DESCRIPTION
**Pull request by qanuj**
migration code for EF6.0.1

### CODE REVIEW

**Comment by doczoidberg** [comment]
Does this code realy work with the client? I think it does only compile but does not work with the client correct?

**Comment by qanuj** [comment]
I used this in our internal projects and seems to be doing great. No issues so far.

**Comment by doczoidberg** [comment]
I tried your fork with MVC5 in a new VS2013 project and getting the error
`Could not load file or assembly System.Net.Http, Version=4.0.0.0`

I have Version 5.0 installed. Any idea?

**Comment by qanuj** [comment]
you would need to add following to assembly bindings in web.config

```
  <dependentAssembly>
    <assemblyIdentity name="System.Web.Http" publicKeyToken="31bf3856ad364e35" />
    <bindingRedirect oldVersion="1.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
  </dependentAssembly>
  <dependentAssembly>
    <assemblyIdentity name="System.Net.Http.Formatting" publicKeyToken="31bf3856ad364e35" />
    <bindingRedirect oldVersion="1.0.0.0-5.0.0.0" newVersion="5.0.0.0" />
  </dependentAssembly>
```

**Comment by doczoidberg** [comment]
Does this also work with web api 2? I have no `GlobalConfiguration` in System.Web.Http

**Comment by qanuj** [comment]
No tried that, but it should work without any issue.

**Comment by jtraband** [comment]
The current Breeze v 1.4.5 supports WebApi2 and EF6 out of the box.

**Pull request closed without merging**
