### PR TITLE
Two bugs related to inheritance

### PR DESCRIPTION
**Pull request by Skielex**
I've come across two bugs when using Breeze, which both seems to be related to inheritance.

The first one is that entities using inheritance doesn't seem to be properly re-constructed in the cache when loaded using the `EntityManager.importEntities` function. Apparently something was missing when remapping navigation properties. The `unattachedMap.getTuples` didn't take into account navigation properties which belonged to the base object. This has been fixed with a new prototype function.

The second issue was the `assignFn` function would sometimes be null when queying the server with a query extending a navigation property, which used inheritance. A simple check `(typeof assignFn === "function")` seems to solve this problem.

//Niels

### CODE REVIEW

**Comment by johnlantz** [comment]
Skielex,

Are you still running into this problem? I ask as we don't see it in the latest build (1.4.1). Will you please check to see if you can replicate the problem without applying this fix?

Thanks,

John

**Comment by Skielex** [comment]
I'll try to test it within the next week. :)

**Comment by Skielex** [comment]
The code below still throws an "undefined is not a function" error, because `assignFn` is undefined. This happens when querying the server for data. However the data seems to be cached corrently even though this exception is thrown.

``` javascript
            if (typeof refValue === "function") {
                mappingContext.deferredFns.push(function () {
                    assignFn(refValue);
                });
                return undefined; // deferred and will be set later;
            }
```

Adding `typeof assignFn === "function"` as I did in my commit seems to fix this problem.

**Comment by Skielex** [comment]
The reconstruction/linking issue seems to have been fixed, or at least I'm not able to reproduce it right now. In fact `getTuples` just seems to return `undefined` all the time now, which means the code shown below is never triggered. Nonetheless the import of the entities seems to go fine. 

``` javascript
            var tuples = unattachedMap.getTuples(entityKey);
            if (tuples) {
                tuples.forEach(function (tpl) {

                    var unattachedChildren = tpl.children.filter(function (e) {
                        return e.entityAspect.entityState !== EntityState.Detached;
                    });

                    var childToParentNp, parentToChildNp;
...
```

**Pull request closed without merging**
